---
- name: Tap the repositories
  homebrew_tap: "tap={{ item }}"
  with_items: brew_taps

- name: Install the homebrew packages
  homebrew: name={{ item }} state=latest
  with_items: brew_packages

- name: Install the cask packages
  homebrew_cask: name={{ item }}
  with_items: cask_packages
