---
# Everything Homebrew-related goes here
- hosts: all
  vars:
    jdks:
    - java
    - java7
  roles:
  - role: osxc.homebrew
  - role: osxc.packages
    brew_taps:
    - caskroom/fonts
    - caskroom/versions
    brew_packages:
    - git
    - zsh
    - vim
    - tmux
    - jenv
    cask_packages:
    - font-inconsolata-for-powerline
    - iterm2
    - macvim
    - intellij-idea
    - vlc
    - sublime-text3
    - google-chrome
    - keka
    - openoffice
  - role: lafarer.osx-jenv