---
# Everything MacBook-related goes here

- hosts: all
  any_errors_fatal: false

  pre_tasks:
  - command: defaults write com.apple.systemuiserver menuExtras -array "/System/Library/CoreServices/Menu Extras/AirPort.menu" "/System/Library/CoreServices/Menu Extras/Battery.menu" "/System/Library/CoreServices/Menu Extras/Clock.menu"

  roles:
  - role: jeremyltn.osx-computername
    computername: unicorn

  # Mac OS defaults configuration
  # See: https://github.com/lafarer/ansible-role-osx-defaults
  - role: lafarer.osx-defaults

    Bluetooth:
      ShowInMenuBar: "true"                         # Show Bluetooth in menu bar
    AppStore:
      ScheduleFrequency: 2                          # Check for software updates (in days)
      AutomaticCheckEnabled: "true"                 # Automatically check for updates
      AutomaticDownload: "true"                     # Download newly available updates in the background
      AutoUpdate: "false"                           # Install app updates
      AutoUpdateRestartRequired: "false"            # Install OSX updates
      ConfigDataInstall: "true"                     # Install system data files
      CriticalUpdateInstall: "true"                 # Install security updates
    DateTime:
      TimeZone: "Europe/London"
      AutomaticDateTime: "on"
      TimeServer: "time.apple.com"                  # Set time server
      AutomaticTimeZone: "true"                     # Set time zome automatically using current location
      DateFormat: 'H:mm'                           # Menu bar clock format ("h:mm": Default, "HH": Use a 24-hour clock, "a": Show AM/PM, "ss": Display the time with seconds
      FlashDateSeparators: "false"                  # Flash the time separators
      IsAnalog: "false"                             # Analog menu bar clock
    Displays:
      AutomaticallyAdjustBrightness: "true"         # Automatically adjust brightness
      AppleFontSmoothing: 2                         # Subpixel font rendering on non-Apple LCDs (0:Disabled, 1:Minimal, 2:Medium, 3:Smoother, 4:Strong)
      DisplayResolutionEnabled: "true"              # Enable HiDPI display modes (requires restart)
      ShowInMenuBarIfPresent: "true"                # Show mirroring options in the menu bar when available
    Dock:
      TileSize: 16                                  # Dock size
      Autohide: "true"                              # Automatically hide and show the Dock
      Magnification: "true"                         # Dock magnification
      LargeSize: 32                                 # Icon size of magnified Dock items
      MinEffect: "genie"                            # Minimization effect: genie, scale, suck
      Orientation: "bottom"                         # Dock orientation: left, bottom, right
      ShowHidden: "true"                            # Display translucent Dock icons for hidden applications
    General:
      AppleAquaColorVariant: 1                      # Set appearance (1: Blue, 6: Graphite)
      AppleHighlightColor: "Blue"                   # Highlight color (Red, Orange, Yellow, Green, Blue, Purple, Pink, Brown, Graphite)
      AppleInterfaceStyle: "Dark"                   # Use Dark menu bar and Dock (Empty or "Dark")
      AutoHideMenuBar: "true"                       # Automatically hide and show the menu bar
      NSTableViewDefaultSizeMode: 1                 # Sidebar icon size (Small: 1, Medium: 2, Large: 3)
      AppleShowScrollBars: "Automatic"              # Scroll bar visibility (WhenScrolling, Automatic, Always)
      NSScrollAnimationEnabled: "true"              # Smooth scrolling (Disable on older Macs)
      NSQuitAlwaysKeepsWindows: "false"             # Close windows when quitting an application
    Keyboard:
      PressAndHoldEnabled: "true"                   # Disable press-and-hold for keys in favor of key repeat
      KeyRepeat: 0                                  # Set key repeat rate (Off: 300000, Slow: 120, Fast: 2)
      InitialKeyRepeat: 10                          # Set delay until repeat, in milliseconds (Long: 120, Short: 15)
      kDim: "true"                                  # Adjust keyboard brightness in low light
      kDimTime: 60                                  # Dim keyboard after idle time (in seconds)
      AppleKeyboardUIMode: 3                        # Full Keyboard Access (1 : Text boxes and lists only, 3 : All controls)
      fnState: "true"                               # Use F1, F2, etc. keys as standard function keys
      AutomaticQuoteSubstitutionEnabled: "false"    # Use smart quotes
      AutomaticDashSubstitutionEnabled: "false"     # Use smart dashes
      AutomaticSpellingCorrectionEnabled: "false"   # Correct spelling automatically
      PowerButtonSleepsSystem: "false"              # Prevent accidental Power button presses from sleeping system
    MissionControl:
      MruSpaces: "true"                             # Automatically rearrange Spaces based on most recent use
      SwitchOnActivate: "true"                      # When switching to an application, switch to a Space with open windows for the application
      GroupByApp: "true"                            # Group windows by application in Mission Control
      SpansDisplays: "true"                         # Displays have separate Spaces

#- role: jeremyltn.osx-sudoers
#  sudoers:
#    manage_sudoers: yes
#    users:
#    - user: "{{ ansible_user_id }}"
#      nopasswd: "yes"

