---
# Everything MacBook-related goes here

- hosts: all
  any_errors_fatal: false

  pre_tasks:
  # Show wifi, battery, clock on the menu
  - command: >
        defaults write com.apple.systemuiserver menuExtras -array
          "/System/Library/CoreServices/Menu Extras/Bluetooth.menu"
          "/System/Library/CoreServices/Menu Extras/AirPort.menu"
          "/System/Library/CoreServices/Menu Extras/Battery.menu"
          "/System/Library/CoreServices/Menu Extras/Clock.menu"

  roles:
  - role: jeremyltn.osx-computername
    computername: unicorn

  # Mac OS defaults configuration
  # See: https://github.com/lafarer/ansible-role-osx-defaults
  - role: lafarer.osx-defaults
    ### AppStore values ###
    AppStore_Enabled: true                          # Enable AppStore configuration
    AppStore_AutomaticCheckEnabled: true            # Automatically check for updates
    AppStore_AutomaticDownload: true                # Download newly available updates in the background
    AppStore_AutoUpdate: false                       # Install app updates
    AppStore_AutoUpdateRestartRequired: false        # Install OSX updates
    AppStore_ConfigDataInstall: true                # Install system data files
    AppStore_CriticalUpdateInstall: true            # Install security updates
    AppStore_ScheduleFrequency: 2                    # Check for software updates (in days)
    AppStore_ShowDebugMenu: true                    # Show debug menu
    ### Bluetooth ###
    Bluetooth_Enabled: true                         # Enable Bluetooth configuration
    Bluetooth_ShowInMenuBar: "true"                 # Show Bluetooth in menu bar
    ### Dashboard ###
    Dashboard_Enabled: true                         # Enable Dashboard configuration
    Dashboard_McxDisabled: true                      # Disable Dashboard
    Dashboard_EnabledState: 1                        # Dashboard state (1: Off, 2: As Space, 3: As Overlay)
    Dashboard_DontShowAsSpace: true                  # Don’t show Dashboard as a Space
    Dashboard_DevMode: false                         # Enable Dashboard dev mode (allows keeping widgets on the desktop)
    ### Date settings ###
    DateTime_Enabled: true                          # Enable Date Time configuration
    DateTime_TimeZone: "Europe/London"             # Set the timezone; see `systemsetup -listtimezones` for other values
    DateTime_AutomaticDateTime: "on"                 # Set date and time automatically (on | off)
    DateTime_TimeServer: "time.apple.com"            # Set time server
    DateTime_AutomaticTimeZone: true                 # Set time zome automatically using current location
    DateTime_DateFormat: "H:mm"                      # Menu bar clock format ("h:mm": Default, "HH": Use a 24-hour clock, "a": Show AM/PM, "ss": Display the time with seconds
    DateTime_FlashDateSeparators: false              # Flash the time separators
    DateTime_IsAnalog: false                         # Analog menu bar clock
    ### Displays config ###
    Displays_Enabled: true                          # Enable Displays configuration
    Displays_AutomaticallyAdjustBrightness: true    # Automatically adjust brightness
    Displays_ShowInMenuBarIfPresent: true            # Show mirroring options in the menu bar when available
    Displays_AppleFontSmoothing: 2                   # Subpixel font rendering on non-Apple LCDs (0:Disabled, 1:Minimal, 2:Medium, 3:Smoother, 4:Strong)
    Displays_DisplayResolutionEnabled: true          # Enable HiDPI display modes (requires restart)
    ### Dock config ###
    Dock_Enabled: true                              # Enable Dock configuration
    Dock_TileSize: 16                                # Dock size
    Dock_Magnification: true                         # Dock magnification
    Dock_LargeSize: 32                              # Icon size of magnified Dock items
    Dock_Orientation: "bottom"                       # Dock orientation: left, bottom, right
    Dock_MinEffect: "genie"                          # Minimization effect: genie, scale, suck
    Dock_AppleActionOnDoubleClick: "Maximize"        # Double-click a window's title title bar to: None, Minimize, Maximize
    Dock_MinimizeToApplication: true                # Minimize windows appliction into icon (true, false)
    Dock_LaunchAnim: true                            # Animate opening applications
    Dock_Autohide: false                             # Automatically hide and show the Dock
    Dock_ShowProcessIndicators: true                 # Show indicator for open applications
    Dock_ShowHidden: true                           # Display translucent Dock icons for hidden applications
    ### General settings ###
    General_Enabled: true                           # Enable General configuration
    General_AppleAquaColorVariant: 6                 # Set appearance (1: Blue, 6: Graphite)
    General_AppleInterfaceStyle: "Dark"                  # Use Dark menu bar and Dock (Empty or "Dark")
    General_AutoHideMenuBar: false                   # Automatically hide and show the menu bar
    General_AppleHighlightColor: "Blue"              # Highlight color (Red, Orange, Yellow, Green, Blue, Purple, Pink, Brown, Graphite)
    General_SidebarIconSize: 1                       # Sidebar icon size (Small: 1, Medium: 2, Large: 3)
    General_AppleShowScrollBars: "Automatic"         # Scroll bar visibility (WhenScrolling, Automatic, Always)
    General_AppleScrollerPagingBehavior: 0           # Click in the scrollbar to (0: Jump to the next page, 1: Jump to the spot that's clicked)
    General_NSCloseAlwaysConfirmsChanges: true      # Ask to keep changes when closing documents
    General_CloseWindowsWhenQuittingApp: true       # Close windows when quitting an application
    General_NSScrollAnimationEnabled: true           # Smooth scrolling (Disable on older Macs)
    ### ICloud ###
    ICloud_Enabled: false                            # Enable iCloud configuration
    ICloud_NSDocumentSaveNewDocumentsToCloud: false   # Save to iCloud by default
    ### Keyboard settings ###
    Keyboard_Enabled: true                            # Enable Keyboard configuration
    Keyboard_KeyRepeat: 0                              # Set key repeat rate (Off: 300000, Slow: 120, Fast: 2)
    Keyboard_InitialKeyRepeat: 10                      # Set delay until repeat, in milliseconds (Long: 120, Short: 15)
    Keyboard_fnState: true                            # Use F1, F2, etc. keys as standard function keys
    Keyboard_kDim: true                               # Adjust keyboard brightness in low light
    Keyboard_kDimTime: 60                               # Dim keyboard after idle time (in seconds, 0 is Never)
    Keyboard_AutomaticSpellingCorrectionEnabled: false # Correct spelling automatically
    Keyboard_AutomaticQuoteSubstitutionEnabled: false  # Use smart quotes
    Keyboard_AutomaticDashSubstitutionEnabled: false   # Use smart dashes
    Keyboard_AppleKeyboardUIMode: 3                    # Full Keyboard Access (1 : Text boxes and lists only, 3 : All controls)
    Keyboard_PowerButtonSleepsSystem: false            # Prevent accidental Power button presses from sleeping system
    Keyboard_PressAndHoldEnabled: true                # Disable press-and-hold for keys in favor of key repeat
    ### Locale settings ###
    LanguageRegion_Enabled: true                    # Enable Language and Region configuration
    # LanguageRegion_Languages: [ "en", "gr" ]            # Does not work! Preferred languages (in order of preference e.g. [ "en", "fr" ])
    LanguageRegion_Locale: "en_GB@currency=GBP"      # Locale and Currency (United States : en_US@currency=USD, Great Britian : en_GB@currency=EUR)
    LanguageRegion_MeasurementUnits: "Centimeters"        # Measure Units (Inches, Centimeters)
    LanguageRegion_Force24HourTime: "true"           # Force 12/24 hour time
    LanguageRegion_MetricUnits: "true"              # Set Metric Units
    ### Mission Control ###
    MissionControl_Enabled: true                    # Enable Mission Control configuration
    MissionControl_MruSpaces: true                  # Automatically rearrange Spaces based on most recent use
    MissionControl_SwitchOnActivate: true            # When switching to an application, switch to a Space with open windows for the application
    MissionControl_GroupByApp: true                  # Group windows by application in Mission Control
    MissionControl_SpansDisplays: true               # Displays have separate Spaces

  # Add current user as passwordless sudoer
  # See: https://galaxy.ansible.com/jeremyltn/osx-sudoers/
  - role: jeremyltn.osx-sudoers
    sudoers:
      manage_sudoers: yes
      users:
      - user: "{{ current_user }}"
        nopasswd: "yes"

