---
# Everything shell-, environment- and VI-related goes here

- hosts: all

  roles:

  # Common env file
  # See: https://galaxy.ansible.com/Meuk/osxc-common-env/#readme
  - role: Meuk.osxc-common-env
    affected_users: [ "{{ current_user}}" ]
    post_tasks:
      - copy: src=../dotfiles/common_env dest=/Users/{{ current_user }}/.common_env backup=yes

  - role: Meuk.osxc-repository
    affected_users: [ "{{ current_user}}" ]
    clone_url: https://github.com/square/maximum-awesome.git
    dest: /Users/{{ current_user }}/.vim
    links:
    - src: vimrc
      dest: /Users/{{ current_user }}/.vimrc
    - src: vimrc.bundles
      dest: /Users/{{ current_user }}/.vimrc.bundles
    - src: tmux.conf
      dest: /Users/{{ current_user }}/.tmux.conf

  - role: Meuk.osxc-repository
    affected_users: [ "{{ current_user}}" ]
    clone_url: https://github.com/VundleVim/Vundle.vim.git
    dest: /Users/{{ current_user }}/.vim/bundle/Vundle.vim

  post_tasks:
  - copy: src=../dotfiles/vimrc.local dest=/Users/{{ current_user }}/.vimrc.local backup=yes
  - copy: src=../dotfiles/vimrc.bundles.local dest=/Users/{{ current_user }}/.vimrc.bundles.local backup=yes
  - copy: src=../dotfiles/tmux.conf.local dest=/Users/{{ current_user }}/.tmux.conf.local backup=yes
  - copy: src=../dotfiles/bash_profile.local dest=/Users/{{ current_user }}/.bash_profile backup=yes
  - copy: src=../dotfiles/bash_sgerogia.local dest=/Users/{{ current_user }}/.bash_sgerogia backup=yes
  - shell: ../scripts/post_setup.sh
